### ISSUE TITLE
types.d.ts seams broken. 

### ISSUE THREAD

**Issue by JimmyBjorklund** [panates/ts-gems#2]
Now using node v22.10.0 (npm v10.9.0)
npm run build

> tsc

node_modules/strict-typed-events/node_modules/ts-gems/lib/types.d.ts:21:17 - error TS2304: Cannot find name 'ReadableStreamGetReaderOptions'.

21       options?: ReadableStreamGetReaderOptions,
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/strict-typed-events/node_modules/ts-gems/lib/types.d.ts:22:8 - error TS2552: Cannot find name 'ReadableStreamReader'. Did you mean 'ReadableStream'?

22     ): ReadableStreamReader<R>;
          ~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/strict-typed-events/node_modules/ts-gems/lib/types.d.ts:21

**Comment by erayhanoglu** [comment]
Hi Jimmy. 
Sorry but i can not reproduce the problem. I ve tested both strict-typed-events and ts-gems libraries. Both is ok.

ReadableStreamGetReaderOptions type is defined in @types/node library. You may clean your node_modules directory and reinstall it.

**Comment by JimmyBjorklund** [comment]
Create a sample
https://github.com/[JimmyBjorklund/ts-gem-test](https://github.com/JimmyBjorklund/ts-gem-test)

**Comment by JimmyBjorklund** [comment]
Looking at other libs thy have this defined 
type ReadableStreamReaderMode = "byob";

interface ReadableStreamGetReaderOptions {
  /**
   * Creates a ReadableStreamBYOBReader and locks the stream to the new reader.
   *
   * This call behaves the same way as the no-argument variant, except that it only works on readable byte streams, i.e. streams which were constructed specifically with the ability to handle "bring your own buffer" reading. The returned BYOB reader provides the ability to directly read individual chunks from the stream via its read() method, into developer-supplied buffers, allowing more precise control over allocation.
   */
  mode?: ReadableStreamReaderMode;
}

type ReadableStreamReader<T> = ReadableStreamDefaultReader<T> | ReadableStreamBYOBReader;

**Comment by JimmyBjorklund** [comment]
https://github.com/panates/ts-gems/pull/3

**Comment by erayhanoglu** [comment]
Adding reference to dom library fixes the issue. New version has been released.

**Comment by JimmyBjorklund** [comment]
Seams to work thanks
